name: aa-tp2
channels:
- anaconda
- conda-forge
- defaults
dependencies:
    - matplotlib
    - seaborn
    - pandas
    - jupyterlab
    - scikit-learn
    - six
    - pydotplus
    - tqdm
    - librosa
    - pip
    - pip:
        - opensmile
